{
  "openapi": "3.0.1",
  "info": {
    "title": "Superhero api",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://visug-ot-apim.azure-api.net/superheroapi"
    }
  ],
  "paths": {
    "/api/SuperHero": {
      "get": {
        "tags": [
          "SuperHero"
        ],
        "summary": "/api/SuperHero - GET",
        "operationId": "get-api-superhero",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "examples": {
                  "default": {
                    "value": null
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "SuperHero"
        ],
        "summary": "/api/SuperHero - POST",
        "operationId": "post-api-superhero",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SuperHero"
              },
              "example": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/SuperHero"
              },
              "example": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/SuperHero"
              },
              "example": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "examples": {
                  "default": {
                    "value": null
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/SuperHero/{id}": {
      "get": {
        "tags": [
          "SuperHero"
        ],
        "summary": "/api/SuperHero/{id} - GET",
        "operationId": "get-api-superhero-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Format - int32.",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/SuperHero"
                },
                "examples": {
                  "default": {
                    "value": null
                  }
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuperHero"
                },
                "example": {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuperHero"
                },
                "example": {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "SuperHero"
        ],
        "summary": "/api/SuperHero/{id} - PUT",
        "operationId": "put-api-superhero-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Format - int32.",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SuperHero"
              },
              "example": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/SuperHero"
              },
              "example": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/SuperHero"
              },
              "example": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "examples": {
                  "default": {
                    "value": null
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "SuperHero"
        ],
        "summary": "/api/SuperHero/{id} - DELETE",
        "operationId": "delete-api-superhero-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Format - int32.",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "examples": {
                  "default": {
                    "value": null
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SuperHero"
                  }
                },
                "example": [
                  {
                    "id": 0,
                    "name": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "place": "string"
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SuperHero": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "firstName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "nullable": true
          },
          "place": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    },
    "securitySchemes": {
      "apiKeyHeader": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      },
      "apiKeyQuery": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "query"
      }
    }
  },
  "security": [
    {
      "apiKeyHeader": [ ]
    },
    {
      "apiKeyQuery": [ ]
    }
  ]
}