{
  "swagger": "2.0",
  "info": {
    "title": "Superhero api",
    "version": "1.0"
  },
  "host": "visug-ot-apim.azure-api.net",
  "basePath": "/superheroapi",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "apiKeyHeader": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "apiKeyQuery": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "query"
    }
  },
  "security": [
    {
      "apiKeyHeader": []
    },
    {
      "apiKeyQuery": []
    }
  ],
  "paths": {
    "/api/SuperHero": {
      "get": {
        "operationId": "get-api-superhero",
        "summary": "/api/SuperHero - GET",
        "tags": [
          "SuperHero"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SuperHero"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ],
              "text/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ]
            }
          }
        }
      },
      "post": {
        "operationId": "post-api-superhero",
        "summary": "/api/SuperHero - POST",
        "tags": [
          "SuperHero"
        ],
        "parameters": [
          {
            "name": "superHero",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/SuperHero"
            }
          }
        ],
        "consumes": [
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SuperHero"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ],
              "text/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ]
            }
          }
        }
      }
    },
    "/api/SuperHero/{id}": {
      "get": {
        "operationId": "get-api-superhero-id",
        "summary": "/api/SuperHero/{id} - GET",
        "tags": [
          "SuperHero"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Format - int32.",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SuperHero"
            },
            "examples": {
              "application/json": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              },
              "text/json": {
                "id": 0,
                "name": "string",
                "firstName": "string",
                "lastName": "string",
                "place": "string"
              }
            }
          }
        }
      },
      "put": {
        "operationId": "put-api-superhero-id",
        "summary": "/api/SuperHero/{id} - PUT",
        "tags": [
          "SuperHero"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Format - int32.",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "superHero",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/SuperHero"
            }
          }
        ],
        "consumes": [
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SuperHero"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ],
              "text/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ]
            }
          }
        }
      },
      "delete": {
        "operationId": "delete-api-superhero-id",
        "summary": "/api/SuperHero/{id} - DELETE",
        "tags": [
          "SuperHero"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Format - int32.",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SuperHero"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ],
              "text/json": [
                {
                  "id": 0,
                  "name": "string",
                  "firstName": "string",
                  "lastName": "string",
                  "place": "string"
                }
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "SuperHero": {
      "type": "object",
      "properties": {
        "id": {
          "format": "int32",
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "place": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "example": {
        "id": 0,
        "name": "string",
        "firstName": "string",
        "lastName": "string",
        "place": "string"
      }
    }
  },
  "tags": []
}